export default {
  nav: {
    home: 'HOME',
    about: 'ABOUT',
    partnership: 'PARTNERSHIP',
    leadershipModel: 'LEADERSHIP MODEL',
    programmes: 'PROGRAMMES',
    alumni: 'ALUMNI',
    approach: 'APPROACH',
    resources: 'RESOURCES',
    faq: 'FAQ',
    contact: 'CONTACT',
    menu: 'Menu',
    close: 'Close',
    login: 'Log in',
  },
  topBar: {
    announcement: 'Nafis Leadership Program Admissions Now Open',
    applyNow: 'Apply now',
  },
  home: {
    title: 'UAE Government Leaders Program',
    description: 'Empowering the next generation of Emirati leaders.',
  },
  metadata: {
    title: 'GLP',
    description: 'Generated by Next.js',
  },
  programs: {
    hero: {
      pill: 'OUR PROGRAMS',
      title: 'Leadership programmes',
      subtitle: 'designed for every stage of your journey',
      description: 'From rising professionals to senior decision-makers, our programmes help shape future-ready leaders who can deliver real impact across government and national development.',
    },
    items: [

      {
        id: 'uaeglp',
        tag: 'FOR EMERGING AND MID-LEVEL LEADERS',
        title: 'UAE Government Leadership Program',
        description: 'A future-focused programme for emerging leaders, UAEGLP prepares emerging leaders to thrive in fast-evolving environments with a curriculum that blends strategy, innovation and applied leadership to accelerate growth and readiness.',
        features: [
          'Strategic leadership training',
          'Mentorship from experienced leaders',
          'Global exposure & benchmarking',
          'Hybrid learning format (online & offline)'
        ],
        meta: [
          { label: 'Duration:', value: '12 months | Part-time' },
          { label: 'Outcome:', value: 'Certification + entry to the Qiyadat alumni network' }
        ],
        action: 'Apply now',
        image: '/images/pro1.png',
        theme: 'white'
      },
      {
        id: 'nafis',
        tag: 'FOR EARLY-CAREER TALENT',
        title: 'Nafis Leadership Program',
        description: "Nafis is built to nurture early-career professionals who show leadership potential. It's a hands-on programme that builds confidence, develops leadership foundations, and provides a national perspective on development and public impact.",
        features: [
          'Personal leadership development',
          'Applied projects and field visits',
          'Strong peer network',
          'Part-time, cohort-based structure'
        ],
        meta: [
          { label: 'Duration:', value: '12 months | Part-time' },
          { label: 'Outcome:', value: 'Certification + alumni access' }
        ],
        action: 'Apply now',
        image: '/images/pro2.png',
        theme: 'green'
      },

      {
        id: 'strategic',
        tag: 'FOR SENIOR LEADERSHIP',
        title: 'Strategic Leaders Program',
        description: 'An ongoing development platform for senior leaders shaping policy at the highest levels. Strategic Leaders is not a public application program; participants are nominated and engage in continuous capacity-building tailored to national priorities.',
        features: [
          'Advanced leadership dialogues',
          'Global and regional insights',
          'Peer exchange and collaboration',
          'Policy and governance focus'
        ],
        meta: [
          { label: 'Format:', value: 'Ongoing annual program' },
          { label: 'Access:', value: 'By nomination through federal entities' }
        ],
        action: 'Nomination by entities',
        actionDisabled: true,
        note: 'Entry is by nomination through federal entities only',
        image: '/images/pro3.png',
        theme: 'green'
      }
    ],
    contact: {
      titleLine1: 'Unsure which programme is',
      titleLine2: 'right for you?',
      description: "Explore in more detail by reaching out to our team. We're here to guide your leadership journey",
      button: 'Contact us'
    }
  },
}
