export default {
  nav: {
    home: 'Home',
    about: 'About',
    partnership: 'Partnership',
    leadershipModel: 'Leadership Model',
    programmes: 'Programmes',
    alumni: 'Alumni',
    approach: 'Approach',
    resources: 'Resources',
    faq: 'FAQ',
    contact: 'Contact',
    menu: 'Menu',
    close: 'Close',
    login: 'Log in',
  },
  topBar: {
    announcement: 'Nafis Leadership Program Admissions Now Open',
    applyNow: 'Apply now',
  },
  home: {
    title: 'Empowering the next generation of leaders',
    description: 'Discover national leadership programmes designed to shape future-ready Emirati talent, aligned with the UAE’s long-term vision and excellence agenda.',
    about: {
      pill: 'ABOUT',
      title: 'The UAE Government Leaders Programme (UAE GLP) is a national initiative dedicated to cultivating Emirati talent for leadership roles across government and beyond',
      description: 'Through advanced training, mentoring, and real-world exposure, GLP develops leaders equipped to navigate tomorrow’s challenges, today.',
    },
    features: [
      {
        icon: "/images/frame1.png",
        text: "Tailored journeys by career stage",
      },
      {
        icon: "/images/frame2.png",
        text: "Flexible format with part-time structure",
      },
      {
        icon: "/images/frame3.png",
        text: "Official certification upon completion",
      },
      {
        icon: "/images/frame4.png",
        text: "Mentorship from government leaders",
      },
      {
        icon: "/images/frame5.png",
        text: "Field visits & international benchmarking",
      },
      {
        icon: "/images/frame6.png",
        text: "Lifelong community via Qiyadat alumni network",
      },
    ],
  },
  metadata: {
    title: 'GLP',
    description: 'Generated by Next.js',
  },
  programs: {
    hero: {
      pill: 'OUR PROGRAMS',
      title: 'Leadership programmes',
      subtitle: 'designed for every stage of your journey',
      description: 'From rising professionals to senior decision-makers, our programmes help shape future-ready leaders who can deliver real impact across government and national development.',
    },
    items: [

      {
        id: 'uaeglp',
        tag: 'FOR EMERGING AND MID-LEVEL LEADERS',
        title: 'UAE Government Leadership Program',
        description: 'A future-focused programme for emerging leaders, UAEGLP prepares emerging leaders to thrive in fast-evolving environments with a curriculum that blends strategy, innovation and applied leadership to accelerate growth and readiness.',
        features: [
          'Strategic leadership training',
          'Mentorship from experienced leaders',
          'Global exposure & benchmarking',
          'Hybrid learning format (online & offline)'
        ],
        meta: [
          { label: 'Duration:', value: '12 months | Part-time' },
          { label: 'Outcome:', value: 'Certification + entry to the Qiyadat alumni network' }
        ],
        action: 'Apply now',
        image: '/images/pro1.png',
        theme: 'white'
      },
      {
        id: 'nafis',
        tag: 'FOR EARLY-CAREER TALENT',
        title: 'Nafis Leadership Program',
        description: "Nafis is built to nurture early-career professionals who show leadership potential. It's a hands-on programme that builds confidence, develops leadership foundations, and provides a national perspective on development and public impact.",
        features: [
          'Personal leadership development',
          'Applied projects and field visits',
          'Strong peer network',
          'Part-time, cohort-based structure'
        ],
        meta: [
          { label: 'Duration:', value: '12 months | Part-time' },
          { label: 'Outcome:', value: 'Certification + alumni access' }
        ],
        action: 'Apply now',
        image: '/images/pro2.png',
        theme: 'green'
      },

      {
        id: 'strategic',
        tag: 'FOR SENIOR LEADERSHIP',
        title: 'Strategic Leaders Program',
        description: 'An ongoing development platform for senior leaders shaping policy at the highest levels. Strategic Leaders is not a public application program; participants are nominated and engage in continuous capacity-building tailored to national priorities.',
        features: [
          'Advanced leadership dialogues',
          'Global and regional insights',
          'Peer exchange and collaboration',
          'Policy and governance focus'
        ],
        meta: [
          { label: 'Format:', value: 'Ongoing annual program' },
          { label: 'Access:', value: 'By nomination through federal entities' }
        ],
        action: 'Nomination by entities',
        actionDisabled: true,
        note: 'Entry is by nomination through federal entities only',
        image: '/images/pro3.png',
        theme: 'green'
      }
    ],
    contact: {
      titleLine1: 'Unsure which programme is',
      titleLine2: 'right for you?',
      description: "Explore in more detail by reaching out to our team. We're here to guide your leadership journey",
      button: 'Contact us'
    }
  },
  footer: {
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    copyright: "© 2025 UAE Government Leaders Program. All rights reserved.",
    description: "UAE Government Leaders Program - Empowering the next generation of Emirati leaders."
  },
  approach: {
    hero: {
      pill: 'OUR APPROACH',
      title: 'How We Build',
      subtitle: 'Future-Ready Leaders',
      description: 'Our leadership development approach is guided by a national vision, powered by innovation, and tailored to real-world government challenges',
      button: 'Explore programmes'
    },
    methodology: {
      title: {
        highlight1: "The UAE Government Leaders Programme (GLP)",
        text1: " follows a comprehensive and ",
        highlight2: "future-focused development model",
        text2: " rooted in the ",
        highlight3: "UAE Government Leadership Model (UAELGM)"
      },
      description1: "Our methodology is designed to equip leaders at every level with the mindset, tools, and capabilities to lead with impact, locally and globally.",
      description2: "Each program is carefully tailored to meet the specific needs of participants, using a blend of:",
      cards: {
        format: "Advanced learning formats",
        frameworks: "Strategic frameworks",
        mentorship: "Mentorship opportunities"
      }
    },
    learningMethodology: {
      label: "LEARNING METHODOLOGY",
      title: {
        line1: {
          text1: "Real ",
          highlight1: "learning.",
          text2: " Real ",
          highlight2: "application.",
        },
        line2: {
          text3: "Real ",
          highlight3: "results"
        }
      },
      description: "We apply modern, flexible learning methods to deliver an engaging and outcome-driven experience. Each participant's journey is structured to combine theory with action, leadership with service, and ambition with accountability."
    },
    learningMethodologyPart2: {
      title: "KEY FORMATS INCLUDE:",
      items: [
        "Interactive workshops and simulations",
        "Capstone projects and applied case work",
        "Local and international field visits",
        "Mentoring and executive coaching",
        "Digital learning modules and gamified tools"
      ],
      description: "All programmes are cohort-based and designed to be part-time, allowing participants to continue in their roles while developing their leadership capacity."
    },
    aboutUAELGM: {
      label: "ABOUT",
      title: {
        text1: "At the heart of every programme is the ",
        highlight1: "UAE Government Leadership Model",
        text2: " (UAELGM), ",
        highlight2: "a set of core values and competencies",
        text3: " that guide the development of all participants"
      },
      description: "This model ensures alignment with the UAE's long-term vision and supports a unified standard of leadership excellence across all sectors.",
      button: "Learn about the model",
      pillarsTitle: "WE FOCUS ON THREE PILLARS:",
      pillars: [
        {
          title: "Leadership Spirit",
          description: "Cultivating emotional intelligence, ownership, and commitment to national service."
        },
        {
          title: "Achievement & Impact",
          description: "Driving performance, innovation, and results within government and organizational settings."
        },
        {
          title: "Future Outlook",
          description: "Empowering leaders to anticipate challenges, embrace change, and shape the future."
        }
      ]
    },
    alumniNetwork: {
      label: "COMMUNITY & ALUMNI NETWORK",
      title: {
        text1: "We believe leadership is a ",
        highlight1: "constant learning process"
      },
      description: "Through the Qiyada digital hub, all program alumni gain access to an active and growing leadership network. This community enables continued development, peer learning, collaboration, and recognition.",
      benefitsTitle: "ALUMNI BENEFITS INCLUDE:",
      benefits: [
        "Access to exclusive forums, leadership talks, and workshops",
        "Professional networking with peers and experts",
        "Collaborative platforms for innovation and national impact",
        "Ongoing learning opportunities, both virtual and in-person"
      ]
    },
    features: [
      {
        icon: "file.png",
        text: "Programmes designed for public sector needs"
      },
      {
        icon: "laptop.png",
        text: "Seamless blend of virtual and real-world learning"
      },
      {
        icon: "link.png",
        text: "Strong ecosystem of mentors, peers, and experts"
      },
      {
        icon: "network.png",
        text: "Aligned with a recognized national framework"
      },
      {
        icon: "users.png",
        text: "Connection to a lifelong leadership community"
      }
    ],
    contact: {
      titleLine1: "Find out where our leadership",
      titleLine2: "journey takes you",
      description: "Explore our programmes and find the one that fits your path",
      button: "Explore programmes"
    }
  },
  partnership: {
    label: "PARTNERSHIP",
    title: {
      text1: "Invest in leadership today for the ",
      highlight1: "ambitions of tomorrow"
    },
    description: "Partner with GLP to co-create tailored leadership programmes that align with your strategic goals and national priorities.",
    button: "Send an inquiry",
    about: {
      label: "ABOUT",
      title: {
        text1: "The UAE Government Leaders Programme ",
        highlight1: "(GLP)",
        text2: " works hand-in-hand with government entities to design and deliver bespoke ",
        highlight2: "leadership development initiatives"
      },
      description: "Every partnership begins with a deep understanding of your organization's objectives, whether that's nurturing emerging talent, preparing your leaders for complex challenges, or closing key capability gaps."
    },
    approach: {
      title: {
        text1: "We follow a ",
        highlight1: "three-step approach",
        text2: " to ensure every tailored program delivers measurable impact"
      },
      steps: [
        {
          number: "01",
          title: "Consultation",
          description: "We begin by working closely with your leadership team to assess your goals, challenges, and context, including talent gaps, strategic priorities, and target demographics."
        },
        {
          number: "02",
          title: "Co-design",
          description: "Based on your needs, we design a program using proven learning models, curriculum design and implementation strategies, drawing on successes from government accelerators, performance programs and sector-specific training."
        },
        {
          number: "03",
          title: "Delivery",
          description: "Our team supports the full rollout, from onboarding participants to managing facilitation, mentorship, and final assessments. Every programme is delivered to the highest standard and adapted for real-world application."
        }
      ]
    },
    offer: {
      pill: "WHAT WE OFFER",
      title: {
        text1: "Unlock ",
        highlight1: "Potential",
        text2: " with GLP's Innovative ",
        highlight2: "Learning Models",
        text3: " and ",
        highlight3: "Digital Tools"
      },
      description: "We also offer digital collaboration opportunities through Qiyadat, our leadership community platform, giving your team ongoing access to support, alumni networks, and curated knowledge exchanges.",
      cards: [
        {
          icon: "/images/development.png",
          text: "Expertise in leadership development at every level"
        },
        {
          icon: "/images/users.png",
          text: "High-level facilitation, coaching, and programme design"
        },
        {
          icon: "/images/target.png",
          text: "Strategic alignment with UAE Vision 2031 and beyond"
        },
        {
          icon: "/images/star.png",
          text: "Visibility and recognition across the GLP ecosystem"
        }
      ]
    }
  }
}
