import './globals.css'
import localFont from 'next/font/local'

const frutiger = localFont({
  src: [
    {
      path: './fonts/FrutigerLTArabic45Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: './fonts/FrutigerLTArabic55Roman.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/FrutigerLTArabic65Bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-frutiger-arabic',
})

export const metadata = {
  title: 'GLP',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html>
      <body className="font-sans">{children}</body>
    </html>
  )
}
