import './globals.css'

export const metadata = {
  title: 'GLP',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body className="font-sans">{children}</body>
    </html>
  )
}
